### PR TITLE
Update momsurffix

### PR DESCRIPTION
**Pull request by zer0k-z**
Ported over changes from https://github.com/GAMMACASE/MomSurfFix

### CODE REVIEW

**Comment by zer0k-z** [comment]
doesn't work.

**Comment by zer0k-z** [comment]
Nevermind it does work.

**Review by Sikarii — APPROVED** [review]
Thanks a lot!

**Comment by Sikarii** [comment]
We should probably release a version for this.
CC @zealain

**Review by GameChaos — APPROVED** [review]

**Pull request merged**
